# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2c0a0f7e2bbd434fe55633ee4e84c6483daaa7dd4f1582f1d578a3607ca72ef2fee5f31a779fb691c2e151c4c9d2ac098ac9a8a551edc3d78dc71147167d7b4

test:
  secret_key_base: 1c72c2bab810bbc10b592753f8aa43d4e3030f52ba49092fe1c47d5aa622d4741179dbf7951a5e3dd8995d9720de8db2088e5d04a78ecf1190cdf12d40224638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
